### ISSUE TITLE
Search results (list) page

### ISSUE THREAD

**Issue by dy-estate** [Estate-DAO/estate-dao-platform-leptos-ssr#17]

**Comment by abhishek-estatedao** [comment]
https://github.com/user-attachments/assets/43312905-1777-4ba2-8dc0-1819af49963b

**Comment by dy-estate** [comment]
Can I get a staging link for this? @abhishek-estatedao

**Comment by dy-estate** [comment]
Pending changes:
- [ ] User should be able to change the search parameters while on this page. When the user clicks on the search bar > this is how the screen should look https://www.figma.com/design/xDmFVOGKA3WeAOLYyLcBrD/Estate-Dao?node-id=204-14&t=V0z1WOwsYmnWUoFz-4. Then once the user clicks the search button, run the query and show results in the same way as done from search on the landing page.
